quiz/urls.py
from django.urls import path
from quiz import views

urlpatterns = [
    path('', views.index, name='index'),
    path('newspapers/', views.NewspaperListView.as_view(), name='newspapers'),
    path('newspapers/add/', views.NewspaperCreate.as_view(), name='newspaper-add'),
    path('newspapers/<int:pk>', views.NewspaperDetailView.as_view(),
         name='newspaper-detail'),
    path('newspaper/<int:pk>/update/',
         views.NewspaperUpdate.as_view(), name='newspaper-update'),
    path('newspapers/<int:pk>/delete/',
         views.NewspaperDelete.as_view(), name='newspaper-delete'),
    path('newsquiz/', views.NewspaperQuizListView.as_view(), name='news-quizs'),
    path('newsquiz/<int:pk>', views.NewspaperQuizDetailView.as_view(),
         name='news-quiz-detail')
]

quiz_results/quiz_results/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

quiz_results/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('quiz/', include('quiz.urls')),
]

from django.views.generic import RedirectView

urlpatterns += [
    path('', RedirectView.as_view(url='/quiz/'))
]

quiz/models.py
from django.db import models
from django.urls import reverse
from django.core.validators import MaxValueValidator
from django.core.exceptions import ValidationError

from datetime import date

# Create your models here.


class Newspaper(models.Model):

    name = models.CharField(
        max_length=100, blank=False, null=True, help_text="Navnet på avisen")

    class Meta:
        verbose_name = "Avis"
        verbose_name_plural = "Aviser"

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('newspaper-detail', args=[str(self.id)])


class NewspaperQuiz(models.Model):

    newspaper = models.ForeignKey(
        Newspaper, on_delete=models.CASCADE, help_text="Avisen")
    max_score = models.IntegerField(help_text="Øverste poenggrense",
                                    validators=[MaxValueValidator(60)], blank=False, default=20)

    class Meta:
        verbose_name = "Avisquis"
        verbose_name_plural = "Avisquizer"

    def __str__(self):
        return "{0}-quiz".format(self.newspaper.name)

    def get_absolute_url(self):
        return reverse('news-quiz-detail', args=[str(self.id)])


class QuizInstance(models.Model):

    newspaper_quiz = models.ForeignKey(NewspaperQuiz, on_delete=models.CASCADE)
    completed_date = models.DateField(default=date.today)
    score = models.IntegerField(default=0, verbose_name="Poeng")

    class Meta:
        verbose_name = "Quiz"
        verbose_name_plural = "Quizer"

    def display_newspaper_name(self):
        return self.newspaper_quiz.newspaper.name

    display_newspaper_name.short_description = "Avis"

    def display_max_score(self):
        return self.newspaper_quiz.max_score

    display_max_score.short_description = "Poenggrense"

    def __str__(self):
        return "{0} ({1})".format(self.newspaper_quiz, self.completed_date)

quiz/forms.py
from django import forms
from .models import QuizInstance


class QuizInstanceForm(forms.ModelForm):
    class Meta:
        model = QuizInstance
        fields = '__all__'

    def clean_score(self):
        cleaned_data = self.cleaned_data
        max_score = cleaned_data.get('newspaper_quiz').max_score
        score = cleaned_data.get('score')
        if score > max_score:
            raise forms.ValidationError(
                'Score exceeds maximum score ({0})'.format(max_score))
        return score

quiz/views.py
from django.views import generic
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.urls import reverse_lazy
from django.shortcuts import render
from .models import Newspaper, NewspaperQuiz, QuizInstance


def index(request):
    """View function for home page of the site."""

    # Generate counts of some of the main objects.
    num_newspapers = Newspaper.objects.all().count()

    context = {
        'num_newspapers': num_newspapers
    }

    return render(request, 'index.html', context=context)


class QuizInstanceListView(generic.ListView):
    model = QuizInstance


class NewspaperListView(generic.ListView):
    model = Newspaper


class NewspaperDetailView(generic.DetailView):
    model = Newspaper


class NewspaperQuizListView(generic.ListView):
    model = NewspaperQuiz


class NewspaperQuizDetailView(generic.DetailView):
    model = NewspaperQuiz


class NewspaperCreate(CreateView):
    model = Newspaper
    fields = '__all__'


class NewspaperUpdate(UpdateView):
    model = Newspaper
    fields = '__all__'


class NewspaperDelete(DeleteView):
    model = Newspaper
    success_url = reverse_lazy('newspapers')

quiz/templates/base_generic.html
<!DOCTYPE html>
<html lang="en">

<head>
  {% block title %}
  <title>Quiz results</title>{% endblock %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO"
    crossorigin="anonymous">
  <!-- Add additional CSS in static file -->
  {% load static %}
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>

<body>
  <div class="container-fluid">
    <div class="row">
      <div class="col-sm-2">
        {% block sidebar %}
        <ul class="sidebar-nav">
          <li>
            <a href="{% url 'index' %}">Home</a>
          </li>
          <li>
            <a href="{% url 'newspapers' %}">All newspapers</a>
          </li>
          <li>
            <a href="{% url 'news-quizs' %}">All quizes</a>
          </li>
        </ul>
        {% endblock %}
      </div>
      <div class="col-sm-10 ">{% block content %}{% endblock %}</div>
    </div>
  </div>
</body>

</html>

quiz/templates/index.html
{% extends "base_generic.html" %} {% block content %}
<h1>Quiz Results home</h1>
<h2>Dynamic content</h2>
<p>The quiz has the following record counts:</p>
<ul>
  <li>
    <strong>Newspapers:</strong> {{ num_newspapers }}
  </li>
</ul>
{% endblock %}

quiz/templates/quiz/newspaper_confirm_delete.html
{% extends "base_generic.html" %} {% block content %}

<h3>Are you sure to want to delete the newspaper {{ newspaper.name }}?</h3>
<form action="" method="post">
  {% csrf_token %}
  <input type="submit" value="Confirm">
</form>

{% endblock content %}

quiz/templates/quiz/newspaper_detail.html
{% extends "base_generic.html" %} {% block content %}

<h1>Newspaper name: {{ newspaper.name }}</h1>

<button type="button" class="btn btn-primary" onclick="location.href='{% url 'newspaper-update' pk=newspaper.pk %}'">Edit</button>
<button type="button" class="btn btn-danger" onclick="location.href='{% url 'newspaper-delete' pk=newspaper.pk %}'">Delete</button>

{% endblock content %}

quiz/templates/quiz/newspaper_form.html
{% extends "base_generic.html" %} {% block content %}
<h1>Newspaper Form</h1>

<form method="post">
  {% csrf_token %} {{ form.as_p }}
  <input type="submit" value="Save">
</form>

{% endblock content %}

quiz/templates/quiz/newspaper_list.html
{% extends "base_generic.html" %} {% block content %}

<h1>Newspaper List</h1>
{% if newspaper_list %}
<ul>
  {% for newspaper in newspaper_list %}
  <li>
    <a href="{{ newspaper.get_absolute_url }}">{{newspaper.name}}</a>
  </li>

  {% endfor %}
</ul>
{% else %}
<p>There are no newspapers in the list.</p>
{% endif %}
<button class="btn btn-primary" onclick="location.href='{% url 'newspaper-add' %}';">Add Newspaper</button>
{% endblock content %}

quiz/templates/quiz/newspaperquiz_detail.html
{% extends "base_generic.html" %} {% block content %}

<h3>Newspaper name: {{ newspaperquiz.newspaper.name }}</h3>
<h3>Maximum score: {{ newspaperquiz.max_score }}</h3>

<ul>
  {% for quiz in newspaperquiz.quizinstance_set.all %}
  <li>Score at {{ quiz.completed_date }}: {{quiz.score}} </li>
  {% endfor %}

</ul>


{% endblock content %}

quiz/templates/quiz/newspaperquiz_list.html
{% extends "base_generic.html" %} {% block content %}

<h1>Newspaper Quiz List</h1>
{% if newspaperquiz_list %}
<ul>
  {% for newspaperquiz in newspaperquiz_list %}
  <li>
    <a href="{{ newspaperquiz.get_absolute_url }}">{{newspaperquiz.newspaper.name}}</a>
  </li>

  {% endfor %}
</ul>
{% else %}
<p>There are no newspapers in the list.</p>
{% endif %} {% endblock content %}